version: '3.8'

services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: <Password>
    ports:
      - "3301:3306"
    volumes:
      - mysql-master-data:/var/lib/mysql
      - ./master.cnf:/etc/mysql/conf.d/my.cnf
      - ~/Desktop/mysql_logs:/var/log/mysql  # Ensure the directory is mounted

  mysql-slave1:
    image: mysql:8.0
    container_name: mysql-slave1
    environment:
      MYSQL_ROOT_PASSWORD: <Password>
    ports:
      - "3302:3306"
    volumes:
      - mysql-slave1-data:/var/lib/mysql
      - ./slave1.cnf:/etc/mysql/conf.d/my.cnf
      - ~/Desktop/mysql_logs:/var/log/mysql  # Ensure the directory is mounted
    depends_on:
      - mysql-master

  mysql-slave2:
    image: mysql:8.0
    container_name: mysql-slave2
    environment:
      MYSQL_ROOT_PASSWORD: <Password>
    ports:
      - "3303:3306"
    volumes:
      - mysql-slave2-data:/var/lib/mysql
      - ./slave2.cnf:/etc/mysql/conf.d/my.cnf
      - ~/Desktop/mysql_logs:/var/log/mysql  # Ensure the directory is mounted
    depends_on:
      - mysql-master

  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mysql-master
      - mysql-slave1
      - mysql-slave2

volumes:
  mysql-master-data:
  mysql-slave1-data:
  mysql-slave2-data:
